services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    network_mode: host
    security_opt:
      - apparmor:unconfined
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/sites-available/default:/etc/nginx/sites-available/default
      - ./start.sh:/usr/local/bin/start.sh
    working_dir: /usr/share/nginx/html
    command: /usr/local/bin/start.sh